# Generated by Django 2.2.1 on 2019-10-06 21:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='user_id',
            field=models.ForeignKey(on_delete=models.SET(-1), to=settings.AUTH_USER_MODEL),
        ),
    ]
