# Generated by Django 2.2.1 on 2019-10-17 03:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='product_id',
            field=models.ForeignKey(on_delete=models.SET(-1), related_name='producto', to='example.Product'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='user_id',
            field=models.ForeignKey(on_delete=models.SET(-1), related_name='usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product_id',
            field=models.ForeignKey(on_delete=models.SET(-1), related_name='productS', to='example.Product'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='sale',
            name='user_id',
            field=models.ForeignKey(on_delete=models.SET(-1), related_name='userSe', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='inventory_id',
            field=models.ForeignKey(on_delete=models.SET(-1), related_name='inventario', to='example.Inventory'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='typee',
            field=models.CharField(max_length=30),
        ),
    ]
