# Generated by Django 2.2.1 on 2019-10-03 15:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User2',
        ),
        migrations.RenameField(
            model_name='user2',
            old_name='status',
            new_name='is_superuser',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='user_id',
            field=models.ForeignKey(on_delete=models.SET(-1), related_name='usuarioI', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sale',
            name='user_id',
            field=models.ForeignKey(on_delete=models.SET(-1), related_name='userSe', to=settings.AUTH_USER_MODEL),
        ),
    ]
