# Generated by Django 2.2.1 on 2019-12-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_auto_20191209_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='sale_id',
            field=models.OneToOneField(on_delete=models.SET(-1), to='example.Sale'),
        ),
        migrations.AlterModelTable(
            name='notificacion',
            table='notificaciones2',
        ),
    ]
