# Generated by Django 2.2.1 on 2019-12-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_auto_20191209_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='sale_id',
            field=models.ForeignKey(on_delete=models.SET(-1), to='example.Sale'),
        ),
    ]
